easy_admin:
  entities:
    User:
        class: App\Entity\User
        form:
          fields:
            - {property: 'email'}
            - {property: 'username'}

        list:
            fields:
              - {property: 'title', label: 'Titre'}
              - {property: 'content', label: 'Contenu'}
              - {property: 'category', label: 'Cat√©gorie'}
              - {property: 'image', type: 'image'}
              - {property: 'createdAt', label: 'Date'}   

            actions:
              - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary'}
              - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}      